fun main() {
    println("Enter the following: ")
    print("Enrollment Number : ")
    var en = readLine()
    print("Student Name : ")
    var name = readLine()
    print("Student Branch : ")
    var sb = readLine()
    print("Student Class : ")
    var sc = readLine()
    print("Student Batch : ")
    var sba = readLine()
    print("Student College Name : ")
    var scn = readLine()
    print("Student University Name : ")
    var sun = readLine()
    print("Student Age : ")
    var age = readLine()

    println("************************")
    println("Student's Information")
    println("Enrollment No : " + en)
    println("Name : " + name)
    println("Age : " + age)
    println("Branch : " + sb)
    println("Class : " + sc)
    println("Batch : " + sba)
    println("College Name : " + scn)
    println("University Name : " + sun)

}